### ISSUE TITLE
Beschädigte PDF Datei

### ISSUE THREAD

**Issue by Luna131313** [MrDroetsch/Blatt2Aufgabe3#1]
Deine PDF-Datei mit den anderen Aufgaben war leider beschädigt und ich konnte sie nicht öffnen. Ich kann die dir aber trotzdem noch bei Gelegenheit korrigieren :)

**Comment by MrDroetsch** [comment]
Vielen Dank dafür!
Ich habe die Datei neu erstellt, auch wenn sie bei mir eigentlich nutzbar war... Hoffentlich ist sie nun auch ohne Fehler hochgeladen worden.

**Comment by MrDroetsch** [comment]
> Deine PDF-Datei mit den anderen Aufgaben war leider beschädigt und ich konnte sie nicht öffnen. Ich kann die dir aber trotzdem noch bei Gelegenheit korrigieren :)

Vielen Dank dafür!
Ich habe die Datei neu erstellt, auch wenn sie bei mir eigentlich nutzbar war... Hoffentlich ist sie nun auch ohne Fehler hochgeladen worden.

[AlgoBlatt02_Riechers.pdf](https://github.com/MrDroetsch/Blatt2Aufgabe3/files/11466984/AlgoBlatt02_Riechers.pdf)
